# Generated by Django 5.2.8 on 2025-12-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_usersignup_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
